name: 'STACS CI'
description: 'Scan source code, binaries, packages, and archives for static credentials.'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  scan-directory:
    description: 'An optional sub-directory to execute the scan in.'
    default: ''
  fail-build:
    description: 'Whether to fail the build on unsupressed finding.'
    default: 'true'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ secrets.github_token }}
    FAIL_BUILD: ${{ inputs.fail-build }}
    SCAN_SUBDIR: ${{ inputs.scan-directory }}
    SCAN_DIR: "/github/workspace"
