name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Github action
    permissions:
        contents: read         # Required to read the repository contents (checkout).
        pull-requests: write   # Required to annotate pull requests with comments.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Prebuild Docker Image
        run: |
          RULES_VERSION="$(head -n1 Dockerfile | cut -d '-' -f 2)"
          pip install .
          STACS_CI_VERSION="$(python -c 'from stacs.ci.__about__ import __version__ ; print(__version__, end="")')"
          docker build -t "stacscan/stacs-ci:${STACS_CI_VERSION}-${RULES_VERSION}" .

      - name: Repository Root
        uses: ./
        with:
          fail-build: false

      - name: Sub Directory
        uses: ./
        with:
          scan-directory: tests/fixtures/ci/
          fail-build: false
