name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validates the Github action
    permissions:
        contents: read         # Required to read the repository contents (checkout).
        pull-requests: write   # Required to annotate pull requests with comments.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute Github CI Integration
        uses: ./
        with:
          scan-directory: tests/fixtures/ci/
          fail-build: false

